defaults:
  run:
    shell: bash
jobs:
  acceptance-test:
    uses: ./.github/workflows/acceptance-test-run.yml
    with:
      deletion-policy: ${{ inputs.deletion-policy }}
      failure-policy: ${{ inputs.failure-policy }}
      tests: ${{ inputs.tests }}
name: Acceptenace Test
on:
  repository_dispatch:
    types: trigger-ga___acceptance-test.yml
