defaults:
  run:
    shell: bash
jobs:
  run:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-duration-seconds: 21600
        role-session-name: github-actions-aws-cf-templates
        role-to-assume: arn:aws:iam::068189904525:role/github-openid-connect
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: corretto
        java-version: '8'
    - continue-on-error: true
      env:
        ACM_CERTIFICATE_ARN: arn:aws:acm:us-east-1:068189904525:certificate/be2a7595-caf3-4c0a-8021-8a3bd70f6e70
        BUCKET_NAME: cf-templates-1a2zmgbg9ut4o-us-east-1
        BUCKET_REGION: us-east-1
        CLOUDFRONT_ACM_CERTIFICATE_ARN: arn:aws:acm:us-east-1:068189904525:certificate/be2a7595-caf3-4c0a-8021-8a3bd70f6e70
        DELETION_POLICY: ${{ inputs.deletion-policy }}
        DOMAIN_SUFFIX: awscftemplates.timeseries.guru
        FAILURE_POLICY: ${{ inputs.failure-policy }}
        HOSTED_ZONE_ID: Z2W7RO1VZ3Q66M
        TEMPLATE_DIR: ../
      run: mvn -B -q surefire-report:report -Dtest=${{ inputs.tests }} -Dsurefire.reportNameSuffix=us-east-1
      working-directory: test
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: acceptance-test-run-us-east-1
        path: 'test/target/surefire-reports/

          test/target/site/

          '
name: Acceptenace Test Run
on:
  repository_dispatch:
    types: trigger-ga___acceptance-test-run.yml
permissions:
  contents: read
  id-token: write
