concurrency: acceptenace-tests-${{ github.ref }}
defaults:
  run:
    shell: bash
jobs:
  acceptance-test:
    uses: ./.github/workflows/acceptance-test-run.yml
    with:
      deletion-policy: delete
      failure-policy: rollback
      tests: '*'
name: Acceptenace Tests
on:
  repository_dispatch:
    types: trigger-ga___acceptance-tests.yml
