concurrency: latest
defaults:
  run:
    shell: bash
jobs:
  latest:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-session-name: github-actions-aws-cf-templates
        role-to-assume: arn:aws:iam::820394158530:role/github-openid-connect
    - continue-on-error: true
      name: latest
      run: 'sed -i "s/__VERSION__/latest/g" ./*/*.yaml

        aws s3 sync --delete --exact-timestamps --exclude ".git/*" --exclude ".github/*"
        --exclude "test/*" --exclude "docs/*" ./ s3://widdix-aws-cf-templates/

        aws s3 sync --delete --exact-timestamps --exclude ".git/*" --exclude ".github/*"
        --exclude "test/*" --exclude "docs/*" ./ s3://widdix-aws-cf-templates-releases-eu-west-1/latest/

        '
name: Latest
on:
  repository_dispatch:
    types: trigger-ga___latest.yml
permissions:
  contents: read
  id-token: write
