defaults:
  run:
    shell: bash
jobs:
  lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - continue-on-error: true
      name: yamlllint
      run: 'pip install yamllint==1.33.0

        yamllint .

        '
    - continue-on-error: true
      name: cfn-lint
      run: 'pip install cfn-lint==0.85.0

        cfn-lint -i W2001 W3045 W4002 W6001 W8003 E3026 -t ''**/*.yaml''

        '
    - continue-on-error: true
      name: license
      run: 'find . -type f -name ''*.yaml'' -not -name ''.readthedocs.yaml'' | while
        read file; do set -ex && grep -q ''LICENSE-2.0'' "$file"; done;

        '
name: Lint
on:
  repository_dispatch:
    types: trigger-ga___lint.yml
permissions:
  contents: read
  id-token: write
